# Generated by Django 5.0.4 on 2024-05-02 16:31

import annotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=annotations.models.upload_to),
        ),
    ]
